## ActivitySim
## See full license in LICENSE.txt.


#HHT_NONE: 0
#HHT_FAMILY_MARRIED: 1
#HHT_FAMILY_MALE: 2
#HHT_FAMILY_FEMALE: 3
#HHT_NONFAMILY_MALE_ALONE: 4
#HHT_NONFAMILY_MALE_NOTALONE: 5
#HHT_NONFAMILY_FEMALE_ALONE: 6
#HHT_NONFAMILY_FEMALE_NOTALONE: 7

# convenience for expression files
HHT_NONFAMILY: [4, 5, 6, 7]
HHT_FAMILY: [1, 2, 3]

PSTUDENT_GRADE_OR_HIGH: 1
PSTUDENT_UNIVERSITY: 2
PSTUDENT_NOT: 3

GRADE_SCHOOL_MAX_AGE: 14
GRADE_SCHOOL_MIN_AGE: 5

SCHOOL_SEGMENT_NONE: 0
SCHOOL_SEGMENT_GRADE: 1
SCHOOL_SEGMENT_HIGH: 2
SCHOOL_SEGMENT_UNIV: 3

INCOME_SEGMENT_LOW: 1
INCOME_SEGMENT_MED: 2
INCOME_SEGMENT_HIGH: 3

PEMPLOY_FULL: 1
PEMPLOY_PART: 2
PEMPLOY_NOT: 3
PEMPLOY_CHILD: 4

PTYPE_FULL: &ptype_full 1
PTYPE_PART: &ptype_part 2
PTYPE_UNIVERSITY: &ptype_university 3
PTYPE_NONWORK: &ptype_nonwork 4
PTYPE_RETIRED: &ptype_retired 5
PTYPE_DRIVING: &ptype_driving 6
PTYPE_SCHOOL: &ptype_school 7
PTYPE_PRESCHOOL:  &ptype_preschool 8

# these appear as column headers in non_mandatory_tour_frequency.csv
PTYPE_NAME:
  *ptype_full: PTYPE_FULL
  *ptype_part: PTYPE_PART
  *ptype_university: PTYPE_UNIVERSITY
  *ptype_nonwork: PTYPE_NONWORK
  *ptype_retired: PTYPE_RETIRED
  *ptype_driving: PTYPE_DRIVING
  *ptype_school: PTYPE_SCHOOL
  *ptype_preschool: PTYPE_PRESCHOOL


CDAP_ACTIVITY_MANDATORY: M
CDAP_ACTIVITY_NONMANDATORY: N
CDAP_ACTIVITY_HOME: H

max_walk_distance: 3
max_bike_distance: 8
costPerMile: 20.54
costShareSr2: 1.75
costShareSr3: 2.50
walkSpeed: 3.00
bikeSpeed: 12.00
driveSpeed: 25.00
schbusSpeed: 20.00  
# RIDEHAIL Settings
Taxi_baseFare: 3.25
Taxi_costPerMile: 2.25
Taxi_costPerMinute: 0.125
Taxi_waitTime_mean:
  1: 5.5
  2: 9.5
  3: 13.3
  4: 17.3
  5: 26.5
Taxi_waitTime_sd: 
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
TNC_single_baseFare: 1.36
TNC_single_costPerMile: 1.09
TNC_single_costPerMinute: 0.28
TNC_single_costMinimum: 7.42
TNC_single_waitTime_mean: 
  1: 3.0
  2: 6.3
  3: 8.4
  4: 8.5
  5: 10.3
TNC_single_waitTime_sd: 
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
TNC_shared_baseFare: 0.68
TNC_shared_costPerMile: 1.06
TNC_shared_costPerMinute: 0.0
TNC_shared_costMinimum: 2.57
# TNC_shared_IVTFactor: 1.5
TNC_shared_waitTime_mean: 
  1: 5.0
  2: 8.0
  3: 11.0
  4: 15.0
  5: 15.0
TNC_shared_waitTime_sd: 
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
min_waitTime: 0
max_waitTime: 50

