## ActivitySim
## See full license in LICENSE.txt.


#HHT_NONE: 0
#HHT_FAMILY_MARRIED: 1
#HHT_FAMILY_MALE: 2
#HHT_FAMILY_FEMALE: 3
#HHT_NONFAMILY_MALE_ALONE: 4
#HHT_NONFAMILY_MALE_NOTALONE: 5
#HHT_NONFAMILY_FEMALE_ALONE: 6
#HHT_NONFAMILY_FEMALE_NOTALONE: 7

# convenience for expression files
HHT_NONFAMILY: [4, 5, 6, 7]
HHT_FAMILY: [1, 2, 3]

PSTUDENT_GRADE_OR_HIGH: 1
PSTUDENT_UNIVERSITY: 2
PSTUDENT_NOT: 3

GRADE_SCHOOL_MAX_AGE: 14
GRADE_SCHOOL_MIN_AGE: 5

SCHOOL_SEGMENT_NONE: 0
SCHOOL_SEGMENT_GRADE: 1
SCHOOL_SEGMENT_HIGH: 2
SCHOOL_SEGMENT_UNIV: 3

INCOME_SEGMENT_LOW: 1
INCOME_SEGMENT_MED: 2
INCOME_SEGMENT_HIGH: 3

PEMPLOY_FULL: 1
PEMPLOY_PART: 2
PEMPLOY_NOT: 3
PEMPLOY_CHILD: 4

PTYPE_FULL: &ptype_full 1
PTYPE_PART: &ptype_part 2
PTYPE_UNIVERSITY: &ptype_university 3
PTYPE_NONWORK: &ptype_nonwork 4
PTYPE_RETIRED: &ptype_retired 5
PTYPE_DRIVING: &ptype_driving 6
PTYPE_SCHOOL: &ptype_school 7
PTYPE_PRESCHOOL:  &ptype_preschool 8

# these appear as column headers in non_mandatory_tour_frequency.csv
PTYPE_NAME:
  *ptype_full: PTYPE_FULL
  *ptype_part: PTYPE_PART
  *ptype_university: PTYPE_UNIVERSITY
  *ptype_nonwork: PTYPE_NONWORK
  *ptype_retired: PTYPE_RETIRED
  *ptype_driving: PTYPE_DRIVING
  *ptype_school: PTYPE_SCHOOL
  *ptype_preschool: PTYPE_PRESCHOOL


CDAP_ACTIVITY_MANDATORY: M
CDAP_ACTIVITY_NONMANDATORY: N
CDAP_ACTIVITY_HOME: H

# % of resident employment (exlude WFH and in-commuting) by county for workplace location choice
TC_ADJUST: 
  17007: 0.878517 #BOONE
  17031: 0.947245 #COOK
  17037: 0.948049 #DEKALB
  17043: 0.947847 #DUPAGE
  17063: 0.915662 #GRUNDY
  17089: 0.936993 #KANE
  17091: 0.889296 #KANKAKEE
  17093: 0.924214 #KENDALL
  55059: 0.916779 #KENOSHA
  17097: 0.927023 #LAKE, IL
  18089: 0.937297 #LAKE, IN
  18091: 0.865526 #LAPORTE
  17099: 0.815812 #LASALLE
  17103: 0.766068 #LEE
  17111: 0.909250 #MCHENRY
  17141: 0.875599 #OGLE
  18127: 0.895274 #PORTER
  55101: 0.860007 #RACINE
  55127: 0.768901 #WALWORTH
  17197: 0.935409 #WILL
  17201: 0.906175 #WINNEBAGO
  0: 1 #EXTERNAL

# tour and trip mode choice
max_walk_distance: 3
max_bike_distance: 8
costPerMile: 20.54
costShareSr2: 1.75
costShareSr3: 2.50
waitThresh: 10.00
walkThresh: 1.50
bikeThresh: 6.00 
walkSpeed: 3.00
bikeSpeed: 12.00
driveSpeed: 25.00
schbusSpeed: 20.00
#drvtrn_distpen_0_multiplier: 270
wlktrn_distpen_max: 15
drvtrn_distpen_max: 15
#busl_ivt_factor: 1.0
#buse_ivt_factor: 1.0
cta_rail_ivt_factor: 0.9
metra_rail_ivt_factor: 0.65
# RIDEHAIL Settings
Taxi_baseFare: 3.25
Taxi_costPerMile: 2.25
Taxi_costPerMinute: 0.125
Taxi_waitTime_mean:
  1: 5.5
  2: 9.5
  3: 13.3
  4: 17.3
  5: 26.5
Taxi_waitTime_sd: 
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
TNC_single_baseFare: 1.36
TNC_single_costPerMile: 1.09
TNC_single_costPerMinute: 0.28
TNC_single_costMinimum: 7.42
TNC_single_waitTime_mean: 
  1: 3.0
  2: 6.3
  3: 8.4
  4: 8.5
  5: 10.3
TNC_single_waitTime_sd: 
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
TNC_shared_baseFare: 0.68
TNC_shared_costPerMile: 1.06
TNC_shared_costPerMinute: 0.0
TNC_shared_costMinimum: 2.57
# TNC_shared_IVTFactor: 1.5
TNC_shared_waitTime_mean: 
  1: 5.0
  2: 8.0
  3: 11.0
  4: 15.0
  5: 15.0
TNC_shared_waitTime_sd: 
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
min_waitTime: 0
max_waitTime: 50
cost_share_s2: 2
cost_share_s3: 3
vot_threshold_low: 8.81
vot_threshold_med: 18.00

# annotate households: area_types less than this are considered urban
urban_threshold: 3
cbd_threshold: 2
rural_threshold: 5

# annotate households: value of time
min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.87
household_median_value_of_time:
  1: 3.61
  2: 7.61
  3: 30.85

# annotate persons: time_factor 
distributed_time_factor_work_mean: 1.0
distributed_time_factor_work_stddev: 0.7
distributed_time_factor_nonwork_mean: 1.0
distributed_time_factor_nonwork_stddev: 0.6
distributed_time_factor_min: 0.1
distributed_time_factor_max: 10