LOGIT_TYPE: NL
#LOGIT_TYPE: MNL

NESTS:
  name: root
  coefficient: coef_nest_root
  alternatives:
      - name: AUTO
        coefficient: coef_nest_AUTO
        alternatives:
          - DRIVEALONE
          - SHAREDRIDE2
          - SHAREDRIDE3
      - name: NONMOTORIZED
        coefficient: coef_nest_NONMOTORIZED
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  coef_nest_TRANSIT
        alternatives:
          - WALK_TRANSIT
          - PNR_TRANSIT
          - KNR_TRANSIT
          - TNC_TRANSIT
      - name: RIDEHAIL
        coefficient: coef_nest_RIDEHAIL
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED
      - name: SCHOOL_BUS
        coefficient: coef_nest_SCHOOL_BUS
        alternatives:
          - SCHBUS
        

SPEC: tour_mode_choice.csv
COEFFICIENTS: tour_mode_choice_coefficients.csv
COEFFICIENT_TEMPLATE: tour_mode_choice_coefficients_template.csv

# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use
    - tours

nontour_preprocessor:
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use

# to reduce memory needs filter chooser table to these fields
LOGSUM_CHOOSER_COLUMNS:
  - tour_type
  - hhsize
  - density_index
  - age
  - age_16_p
  - age_16_to_19
  - auto_ownership
  - number_of_participants
  - tour_category
  - num_workers
  - free_parking_at_work
  - income
  - time_factor_work
  - time_factor_nonwork
  - demographic_segment
  - is_student

MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
