SPEC: trip_mode_choice.csv
COEFFICIENTS: trip_mode_choice_coefficients.csv
COEFFICIENT_TEMPLATE: trip_mode_choice_coefficients_template.csv

LOGIT_TYPE: NL

NESTS:
  name: root
  coefficient: coef_nest_root
  alternatives:
      - name: AUTO
        coefficient: coef_nest_AUTO
        alternatives:
            - DRIVEALONE
            - SHAREDRIDE2
            - SHAREDRIDE3
      - name: NONMOTORIZED
        coefficient: coef_nest_NONMOTORIZED
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  coef_nest_TRANSIT
        alternatives:
          - WALK_TRANSIT
          - PNR_TRANSIT
          - KNR_TRANSIT
          - TNC_TRANSIT
      - name: RIDEHAIL
        coefficient: coef_nest_RIDEHAIL
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED
      - name: SCHOOL_BUS
        coefficient: coef_nest_SCHOOL_BUS
        alternatives:
          - SCHBUS

CONSTANTS:
  orig_col_name: origin
  dest_col_name: destination
  waitThresh: 10.00
  walkThresh: 1.00
  bikeThresh: 6.00
  I_MODE_MAP:
    DRIVEALONE: 1
    SHAREDRIDE2: 2
    SHAREDRIDE3: 3
    WALK: 4
    BIKE: 5
    WALK_TRANSIT: 6
    PNR_TRANSIT: 7
    KNR_TRANSIT: 8
    TNC_TRANSIT: 9
    TAXI: 10
    TNC_SINGLE: 11
    TNC_SHARED: 12
    SCHBUS: 13
  I_SOV_MODES: [1]
  I_SR2_MODES: [2]
  I_SR3P_MODES: [3]
  I_AUTO_MODES: [1, 2, 3]
  I_WALK_MODE: 4
  I_BIKE_MODE: 5
  I_WALK_TRANSIT_MODES: [6]
  I_DRIVE_TRANSIT_MODES: [7, 8, 9]
  I_PNR_TRANSIT: 7
  I_KNR_TRANSIT: 8
  I_TNC_TRANSIT: 9
  I_TNC_TRN: 9
  I_RIDE_HAIL_MODES: [10, 11, 12]
  I_SCHBUS_MODE: 13
  origin_density_index_multiplier: -15
  origin_density_index_max: -15
  #max_walk_time: 60


# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: trip_mode_choice_annotate_trips_preprocessor
  DF: df
  TABLES:
    - land_use
    - tours

# to reduce memory needs filter chooser table to these fields
TOURS_MERGED_CHOOSER_COLUMNS:
  - hhsize
  - age
  - auto_ownership
  - number_of_participants
  - tour_category
  - parent_tour_id
  - tour_mode
  - duration
  - tour_type
  - free_parking_at_work
  - income
  - time_factor_work
  - time_factor_nonwork  
#  - demographic_segment

MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum

CHOOSER_COLS_TO_KEEP:
  - vot_da