
# borrowed from free parking model

SPEC: work_from_home.csv
COEFFICIENTS: work_from_home_coefficients.csv

#LOGIT_TYPE: NL
LOGIT_TYPE: MNL

WORK_FROM_HOME_ALT: 0

DEST_CHOICE_COLUMN_NAME: workplace_zone_id
CHOOSER_FILTER_COLUMN_NAME: is_worker