# read trips table post preprocessor and run expressions to code
# additional data fields, with one data fields for each matrix specified below

preprocessor:
  SPEC: write_trip_matrices_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - tours
    - households

# divide trip counts by household expansion factor
HH_EXPANSION_WEIGHT_COL: sample_rate  # added when households read in

# save preprocessed trips table to pipeline if desired
SAVE_TRIPS_TABLE: True

MATRICES:
  #EA
  - file_name: trips_ea_taz.omx
    tables:
      - name: SOV_NT_L_EA
        data_field: SOV_NT_L_EA
      - name: SOV_TR_L_EA
        data_field: SOV_TR_L_EA
      - name: HOV2_L_EA
        data_field: HOV2_L_EA
      - name: HOV3_L_EA
        data_field: HOV3_L_EA
      - name: SOV_NT_M_EA
        data_field: SOV_NT_M_EA
      - name: SOV_TR_M_EA
        data_field: SOV_TR_M_EA
      - name: HOV2_M_EA
        data_field: HOV2_M_EA
      - name: HOV3_M_EA
        data_field: HOV3_M_EA
      - name: SOV_NT_H_EA
        data_field: SOV_NT_H_EA
      - name: SOV_TR_H_EA
        data_field: SOV_TR_H_EA
      - name: HOV2_H_EA
        data_field: HOV2_H_EA
      - name: HOV3_H_EA
        data_field: HOV3_H_EA
      - name: WALK_EA
        data_field: WALK_EA
      - name: BIKE_EA
        data_field: BIKE_EA
      - name: SCHBUS_EA
        data_field: SCHBUS_EA

  #AM
  - file_name: trips_am_taz.omx
    tables:
      - name: SOV_NT_L_AM
        data_field: SOV_NT_L_AM
      - name: SOV_TR_L_AM
        data_field: SOV_TR_L_AM
      - name: HOV2_L_AM
        data_field: HOV2_L_AM
      - name: HOV3_L_AM
        data_field: HOV3_L_AM
      - name: SOV_NT_M_AM
        data_field: SOV_NT_M_AM
      - name: SOV_TR_M_AM
        data_field: SOV_TR_M_AM
      - name: HOV2_M_AM
        data_field: HOV2_M_AM
      - name: HOV3_M_AM
        data_field: HOV3_M_AM
      - name: SOV_NT_H_AM
        data_field: SOV_NT_H_AM
      - name: SOV_TR_H_AM
        data_field: SOV_TR_H_AM
      - name: HOV2_H_AM
        data_field: HOV2_H_AM
      - name: HOV3_H_AM
        data_field: HOV3_H_AM
      - name: WALK_AM
        data_field: WALK_AM
      - name: BIKE_AM
        data_field: BIKE_AM
      - name: SCHBUS_AM
        data_field: SCHBUS_AM
        
  - file_name: trn_am_taz.omx
    tables:       
      - name: TRN_WALK_L_AM
        data_field: TRN_WALK_L_AM
      - name: TRN_PNROUT_L_AM
        data_field: TRN_PNROUT_L_AM
      - name: TRN_PNRIN_L_AM
        data_field: TRN_PNRIN_L_AM        
      - name: TRN_KNROUT_L_AM
        data_field: TRN_KNROUT_L_AM
      - name: TRN_KNRIN_L_AM
        data_field: TRN_KNRIN_L_AM        
      - name: TRN_TNCOUT_L_AM
        data_field: TRN_TNCOUT_L_AM
      - name: TRN_TNCIN_L_AM
        data_field: TRN_TNCIN_L_AM        
      - name: TRN_TOT_L_AM
        data_field: TRN_TOT_L_AM
      - name: TRN_WALK_M_AM
        data_field: TRN_WALK_M_AM
      - name: TRN_PNROUT_M_AM
        data_field: TRN_PNROUT_M_AM
      - name: TRN_PNRIN_M_AM
        data_field: TRN_PNRIN_M_AM        
      - name: TRN_KNROUT_M_AM
        data_field: TRN_KNROUT_M_AM
      - name: TRN_KNRIN_M_AM
        data_field: TRN_KNRIN_M_AM        
      - name: TRN_TNCOUT_M_AM
        data_field: TRN_TNCOUT_M_AM
      - name: TRN_TNCIN_M_AM
        data_field: TRN_TNCIN_M_AM        
      - name: TRN_TOT_M_AM
        data_field: TRN_TOT_M_AM
      - name: TRN_WALK_H_AM
        data_field: TRN_WALK_H_AM
      - name: TRN_PNROUT_H_AM
        data_field: TRN_PNROUT_H_AM
      - name: TRN_PNRIN_H_AM
        data_field: TRN_PNRIN_H_AM        
      - name: TRN_KNROUT_H_AM
        data_field: TRN_KNROUT_H_AM
      - name: TRN_KNRIN_H_AM
        data_field: TRN_KNRIN_H_AM        
      - name: TRN_TNCOUT_H_AM
        data_field: TRN_TNCOUT_H_AM
      - name: TRN_TNCIN_H_AM
        data_field: TRN_TNCIN_H_AM        
      - name: TRN_TOT_H_AM
        data_field: TRN_TOT_H_AM
  
  #MM
  - file_name: trips_mm_taz.omx
    tables:
      - name: SOV_NT_L_MM
        data_field: SOV_NT_L_MM
      - name: SOV_TR_L_MM
        data_field: SOV_TR_L_MM
      - name: HOV2_L_MM
        data_field: HOV2_L_MM
      - name: HOV3_L_MM
        data_field: HOV3_L_MM
      - name: SOV_NT_M_MM
        data_field: SOV_NT_M_MM
      - name: SOV_TR_M_MM
        data_field: SOV_TR_M_MM
      - name: HOV2_M_MM
        data_field: HOV2_M_MM
      - name: HOV3_M_MM
        data_field: HOV3_M_MM
      - name: SOV_NT_H_MM
        data_field: SOV_NT_H_MM
      - name: SOV_TR_H_MM
        data_field: SOV_TR_H_MM
      - name: HOV2_H_MM
        data_field: HOV2_H_MM
      - name: HOV3_H_MM
        data_field: HOV3_H_MM
      - name: WALK_MM
        data_field: WALK_MM
      - name: BIKE_MM
        data_field: BIKE_MM
      - name: SCHBUS_MM
        data_field: SCHBUS_MM

  #MD
  - file_name: trips_md_taz.omx
    tables:
      - name: SOV_NT_L_MD
        data_field: SOV_NT_L_MD
      - name: SOV_TR_L_MD
        data_field: SOV_TR_L_MD
      - name: HOV2_L_MD
        data_field: HOV2_L_MD
      - name: HOV3_L_MD
        data_field: HOV3_L_MD
      - name: SOV_NT_M_MD
        data_field: SOV_NT_M_MD
      - name: SOV_TR_M_MD
        data_field: SOV_TR_M_MD
      - name: HOV2_M_MD
        data_field: HOV2_M_MD
      - name: HOV3_M_MD
        data_field: HOV3_M_MD
      - name: SOV_NT_H_MD
        data_field: SOV_NT_H_MD
      - name: SOV_TR_H_MD
        data_field: SOV_TR_H_MD
      - name: HOV2_H_MD
        data_field: HOV2_H_MD
      - name: HOV3_H_MD
        data_field: HOV3_H_MD
      - name: WALK_MD
        data_field: WALK_MD
      - name: BIKE_MD
        data_field: BIKE_MD
      - name: SCHBUS_MD
        data_field: SCHBUS_MD
 
  - file_name: trn_md_taz.omx
    tables:                
      - name: TRN_WALK_L_MD
        data_field: TRN_WALK_L_MD
      - name: TRN_PNROUT_L_MD
        data_field: TRN_PNROUT_L_MD
      - name: TRN_PNRIN_L_MD
        data_field: TRN_PNRIN_L_MD        
      - name: TRN_KNROUT_L_MD
        data_field: TRN_KNROUT_L_MD
      - name: TRN_KNRIN_L_MD
        data_field: TRN_KNRIN_L_MD        
      - name: TRN_TNCOUT_L_MD
        data_field: TRN_TNCOUT_L_MD
      - name: TRN_TNCIN_L_MD
        data_field: TRN_TNCIN_L_MD        
      - name: TRN_TOT_L_MD
        data_field: TRN_TOT_L_MD
      - name: TRN_WALK_M_MD
        data_field: TRN_WALK_M_MD
      - name: TRN_PNROUT_M_MD
        data_field: TRN_PNROUT_M_MD
      - name: TRN_PNRIN_M_MD
        data_field: TRN_PNRIN_M_MD        
      - name: TRN_KNROUT_M_MD
        data_field: TRN_KNROUT_M_MD
      - name: TRN_KNRIN_M_MD
        data_field: TRN_KNRIN_M_MD        
      - name: TRN_TNCOUT_M_MD
        data_field: TRN_TNCOUT_M_MD
      - name: TRN_TNCIN_M_MD
        data_field: TRN_TNCIN_M_MD        
      - name: TRN_TOT_M_MD
        data_field: TRN_TOT_M_MD
      - name: TRN_WALK_H_MD
        data_field: TRN_WALK_H_MD
      - name: TRN_PNROUT_H_MD
        data_field: TRN_PNROUT_H_MD
      - name: TRN_PNRIN_H_MD
        data_field: TRN_PNRIN_H_MD        
      - name: TRN_KNROUT_H_MD
        data_field: TRN_KNROUT_H_MD
      - name: TRN_KNRIN_H_MD
        data_field: TRN_KNRIN_H_MD        
      - name: TRN_TNCOUT_H_MD
        data_field: TRN_TNCOUT_H_MD
      - name: TRN_TNCIN_H_MD
        data_field: TRN_TNCIN_H_MD        
      - name: TRN_TOT_H_MD
        data_field: TRN_TOT_H_MD

  #AF
  - file_name: trips_af_taz.omx
    tables:
      - name: SOV_NT_L_AF
        data_field: SOV_NT_L_AF
      - name: SOV_TR_L_AF
        data_field: SOV_TR_L_AF
      - name: HOV2_L_AF
        data_field: HOV2_L_AF
      - name: HOV3_L_AF
        data_field: HOV3_L_AF
      - name: SOV_NT_M_AF
        data_field: SOV_NT_M_AF
      - name: SOV_TR_M_AF
        data_field: SOV_TR_M_AF
      - name: HOV2_M_AF
        data_field: HOV2_M_AF
      - name: HOV3_M_AF
        data_field: HOV3_M_AF
      - name: SOV_NT_H_AF
        data_field: SOV_NT_H_AF
      - name: SOV_TR_H_AF
        data_field: SOV_TR_H_AF
      - name: HOV2_H_AF
        data_field: HOV2_H_AF
      - name: HOV3_H_AF
        data_field: HOV3_H_AF
      - name: WALK_AF
        data_field: WALK_AF
      - name: BIKE_AF
        data_field: BIKE_AF
      - name: SCHBUS_AF
        data_field: SCHBUS_AF

  #PM
  - file_name: trips_pm_taz.omx
    tables:
      - name: SOV_NT_L_PM
        data_field: SOV_NT_L_PM
      - name: SOV_TR_L_PM
        data_field: SOV_TR_L_PM
      - name: HOV2_L_PM
        data_field: HOV2_L_PM
      - name: HOV3_L_PM
        data_field: HOV3_L_PM
      - name: SOV_NT_M_PM
        data_field: SOV_NT_M_PM
      - name: SOV_TR_M_PM
        data_field: SOV_TR_M_PM
      - name: HOV2_M_PM
        data_field: HOV2_M_PM
      - name: HOV3_M_PM
        data_field: HOV3_M_PM
      - name: SOV_NT_H_PM
        data_field: SOV_NT_H_PM
      - name: SOV_TR_H_PM
        data_field: SOV_TR_H_PM
      - name: HOV2_H_PM
        data_field: HOV2_H_PM
      - name: HOV3_H_PM
        data_field: HOV3_H_PM
      - name: WALK_PM
        data_field: WALK_PM
      - name: BIKE_PM
        data_field: BIKE_PM
      - name: SCHBUS_PM
        data_field: SCHBUS_PM

  - file_name: trn_pm_taz.omx
    tables:                
      - name: TRN_WALK_L_PM
        data_field: TRN_WALK_L_PM
      - name: TRN_PNROUT_L_PM
        data_field: TRN_PNROUT_L_PM
      - name: TRN_PNRIN_L_PM
        data_field: TRN_PNRIN_L_PM        
      - name: TRN_KNROUT_L_PM
        data_field: TRN_KNROUT_L_PM
      - name: TRN_KNRIN_L_PM
        data_field: TRN_KNRIN_L_PM        
      - name: TRN_TNCOUT_L_PM
        data_field: TRN_TNCOUT_L_PM
      - name: TRN_TNCIN_L_PM
        data_field: TRN_TNCIN_L_PM        
      - name: TRN_TOT_L_PM
        data_field: TRN_TOT_L_PM
      - name: TRN_WALK_M_PM
        data_field: TRN_WALK_M_PM
      - name: TRN_PNROUT_M_PM
        data_field: TRN_PNROUT_M_PM
      - name: TRN_PNRIN_M_PM
        data_field: TRN_PNRIN_M_PM        
      - name: TRN_KNROUT_M_PM
        data_field: TRN_KNROUT_M_PM
      - name: TRN_KNRIN_M_PM
        data_field: TRN_KNRIN_M_PM        
      - name: TRN_TNCOUT_M_PM
        data_field: TRN_TNCOUT_M_PM
      - name: TRN_TNCIN_M_PM
        data_field: TRN_TNCIN_M_PM        
      - name: TRN_TOT_M_PM
        data_field: TRN_TOT_M_PM
      - name: TRN_WALK_H_PM
        data_field: TRN_WALK_H_PM
      - name: TRN_PNROUT_H_PM
        data_field: TRN_PNROUT_H_PM
      - name: TRN_PNRIN_H_PM
        data_field: TRN_PNRIN_H_PM        
      - name: TRN_KNROUT_H_PM
        data_field: TRN_KNROUT_H_PM
      - name: TRN_KNRIN_H_PM
        data_field: TRN_KNRIN_H_PM        
      - name: TRN_TNCOUT_H_PM
        data_field: TRN_TNCOUT_H_PM
      - name: TRN_TNCIN_H_PM
        data_field: TRN_TNCIN_H_PM        
      - name: TRN_TOT_H_PM
        data_field: TRN_TOT_H_PM

  #EV
  - file_name: trips_ev_taz.omx
    tables:
      - name: SOV_NT_L_EV
        data_field: SOV_NT_L_EV
      - name: SOV_TR_L_EV
        data_field: SOV_TR_L_EV
      - name: HOV2_L_EV
        data_field: HOV2_L_EV
      - name: HOV3_L_EV
        data_field: HOV3_L_EV
      - name: SOV_NT_M_EV
        data_field: SOV_NT_M_EV
      - name: SOV_TR_M_EV
        data_field: SOV_TR_M_EV
      - name: HOV2_M_EV
        data_field: HOV2_M_EV
      - name: HOV3_M_EV
        data_field: HOV3_M_EV
      - name: SOV_NT_H_EV
        data_field: SOV_NT_H_EV
      - name: SOV_TR_H_EV
        data_field: SOV_TR_H_EV
      - name: HOV2_H_EV
        data_field: HOV2_H_EV
      - name: HOV3_H_EV
        data_field: HOV3_H_EV
      - name: WALK_EV
        data_field: WALK_EV
      - name: BIKE_EV
        data_field: BIKE_EV
      - name: SCHBUS_EV
        data_field: SCHBUS_EV
                
  #NT
  - file_name: trips_nt_taz.omx
    tables:
      - name: SOV_NT_L_NT
        data_field: SOV_NT_L_NT
      - name: SOV_TR_L_NT
        data_field: SOV_TR_L_NT
      - name: HOV2_L_NT
        data_field: HOV2_L_NT
      - name: HOV3_L_NT
        data_field: HOV3_L_NT
      - name: SOV_NT_M_NT
        data_field: SOV_NT_M_NT
      - name: SOV_TR_M_NT
        data_field: SOV_TR_M_NT
      - name: HOV2_M_NT
        data_field: HOV2_M_NT
      - name: HOV3_M_NT
        data_field: HOV3_M_NT
      - name: SOV_NT_H_NT
        data_field: SOV_NT_H_NT
      - name: SOV_TR_H_NT
        data_field: SOV_TR_H_NT
      - name: HOV2_H_NT
        data_field: HOV2_H_NT
      - name: HOV3_H_NT
        data_field: HOV3_H_NT
      - name: WALK_NT
        data_field: WALK_NT
      - name: BIKE_NT
        data_field: BIKE_NT
      - name: SCHBUS_NT
        data_field: SCHBUS_NT

  - file_name: trn_nt_taz.omx
    tables:                
      - name: TRN_WALK_L_NT
        data_field: TRN_WALK_L_NT
      - name: TRN_PNROUT_L_NT
        data_field: TRN_PNROUT_L_NT
      - name: TRN_PNRIN_L_NT
        data_field: TRN_PNRIN_L_NT        
      - name: TRN_KNROUT_L_NT
        data_field: TRN_KNROUT_L_NT
      - name: TRN_KNRIN_L_NT
        data_field: TRN_KNRIN_L_NT        
      - name: TRN_TNCOUT_L_NT
        data_field: TRN_TNCOUT_L_NT
      - name: TRN_TNCIN_L_NT
        data_field: TRN_TNCIN_L_NT        
      - name: TRN_TOT_L_NT
        data_field: TRN_TOT_L_NT
      - name: TRN_WALK_M_NT
        data_field: TRN_WALK_M_NT
      - name: TRN_PNROUT_M_NT
        data_field: TRN_PNROUT_M_NT
      - name: TRN_PNRIN_M_NT
        data_field: TRN_PNRIN_M_NT        
      - name: TRN_KNROUT_M_NT
        data_field: TRN_KNROUT_M_NT
      - name: TRN_KNRIN_M_NT
        data_field: TRN_KNRIN_M_NT        
      - name: TRN_TNCOUT_M_NT
        data_field: TRN_TNCOUT_M_NT
      - name: TRN_TNCIN_M_NT
        data_field: TRN_TNCIN_M_NT        
      - name: TRN_TOT_M_NT
        data_field: TRN_TOT_M_NT
      - name: TRN_WALK_H_NT
        data_field: TRN_WALK_H_NT
      - name: TRN_PNROUT_H_NT
        data_field: TRN_PNROUT_H_NT
      - name: TRN_PNRIN_H_NT
        data_field: TRN_PNRIN_H_NT        
      - name: TRN_KNROUT_H_NT
        data_field: TRN_KNROUT_H_NT
      - name: TRN_KNRIN_H_NT
        data_field: TRN_KNRIN_H_NT        
      - name: TRN_TNCOUT_H_NT
        data_field: TRN_TNCOUT_H_NT
      - name: TRN_TNCIN_H_NT
        data_field: TRN_TNCIN_H_NT        
      - name: TRN_TOT_H_NT
        data_field: TRN_TOT_H_NT


CONSTANTS:
  time_periods:
    # auto
    #  periods: [0, 4, 5, 7, 8, 12, 14, 16, 18, 24]
    #labels: &skim_time_period_labels ['VE', 'EA', 'AM', 'MM', 'MD', 'AF', 'PM', 'EV', 'NT']
    # VE = 3a - 6a (same skim data as NT)
    # EA = 6a - 7a
    # AM = 7a - 9a
    # MM = 9a - 10a
    # MD = 10a - 2p
    # AF = 2p - 4p
    # PM = 4p - 6p
    # EV = 6p - 8p
    # NT = 8p - 3a
    VE:
      first_hour: 1
      last_hour: 6
    EA:
      first_hour: 7
      last_hour: 8
    AM:
      first_hour: 9
      last_hour: 12
    MM:
      first_hour: 13
      last_hour: 14
    MD:
      first_hour: 15
      last_hour: 22
    AF:
      first_hour: 23
      last_hour: 26
    PM:
      first_hour: 27
      last_hour: 30
    EV:
      first_hour: 31
      last_hour: 34
    NT:
      first_hour: 35
      last_hour: 48
    # transit
    #  periods: [0, 4, 5, 7, 8, 12, 14, 16, 18, 24]
    #labels: &skim_time_period_labels ['TVE', 'TAM', 'TMD', 'TPM', 'TNT']
    # TVE = 3a - 6a (same skim data as NT)
    # TAM = 6a - 9a
    # TMD = 9a - 4p
    # TPM = 4p - 6p
    # TNT = 6p - 3a
    TVE:
      first_hour: 1
      last_hour: 6
    TAM:
      first_hour: 7
      last_hour: 12
    TMD:
      first_hour: 13
      last_hour: 26
    TPM:
      first_hour: 27
      last_hour: 30
    TNT:
      first_hour: 31
      last_hour: 48
  # SHARED2 and SHARED3 Occupancies
  OCC_SHARED2: 2.0
  OCC_SHARED3: 3.33
