inherit_settings: True

# area_types less than this are considered urban
urban_threshold: 2
cbd_threshold: 1
rural_threshold: 4

# - value of time
min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.87

household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86

fail_fast: True
# - ------------------------- dev config
multiprocess: False
strict: False
mem_tick: 30
use_shadow_pricing: False
## - example sample
households_sample_size: 0
chunk_size: 0
#chunk_training_mode: training
num_processes: 1 
# - tracing
trace_od:
trace_hh_id:


trace_hh_id:

# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      HHID: household_id
      PERSONS: hhsize
      hworkers: num_workers
      VEHICL: auto_ownership
      TAZ: home_zone_id
      HINC: income
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      PERID: person_id
      AGE: age
      SEX: sex
    keep_columns:
      - household_id
      - age
      - PNUM
      - sex
      - pemploy
      - pstudent
      - ptype
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    rename_columns:
      maz: zone_id
      COUNTY: county_id
      hshld: TOTHH
      emp: TOTEMP
    keep_columns:
      - taz
      - TOTHH
      - acres
      - areatype
      - TOTEMP
      - construc
      - manufac
      - tcu
      - wholesl
      - retail
      - fire
      - service
      - k8_enroll
      - highschool_enroll
      - lg_college
      - small_coll

output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips

models:
  ### mp_initialize step
  - initialize_landuse
  - initialize_households
  - compute_accessibility
  # --- STATIC cache prebuild steps
  # single-process step to create attribute_combination list
  - initialize_los
  # multi-processable step to build STATIC cache
  # (this step is a NOP if cache already exists and network_los.rebuild_tvpb_cache setting is False)
  - initialize_tvpb
  # ---
  ### mp_households step
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  ### mp_summarize_step
  - write_data_dictionary
  - track_skim_usage
  - write_trip_matrices
  - write_tables

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_households
    begin: school_location
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary
output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
#    - school_shadow_prices
#    - workplace_shadow_prices
    - joint_tour_participants

# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
#read_skim_cache: True
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
#write_skim_cache: True